"""
Type definitions for training module.

This module contains shared types used across the training package,
specifically designed to avoid torch imports in scan workers.
"""

import pandas as pd
from dataclasses import dataclass
from typing import Dict, Optional

from ..core.channel import Channel
from ..features.full_features import FullFeatures
from .labels import ChannelLabels


@dataclass
class ChannelSample:
    """
    A single training sample consisting of a valid channel + its features and labels.

    Supports multi-window channel detection where channels are detected using
    different lookback window sizes, and the best window is selected.

    Attributes:
        timestamp: When this channel ends (last bar of detection window)
        channel_end_idx: Index in the full dataset where channel ends
        channel: The best detected Channel object (from best_window)
        features: FullFeatures extracted at channel end (from best_window)
        labels: Dict mapping TF names to ChannelLabels for the best window.
                Each TF has independently generated labels with proper scaling.
                Some TFs may have None if channel detection failed at that TF.
        channels: Dict mapping window sizes to Channel objects. Contains all
                  detected channels from different window sizes (e.g., {50: Channel, 100: Channel}).
        best_window: The window size that was selected as the best channel.
                     The `channel` field contains `channels[best_window]`.
        labels_per_window: Dict mapping window sizes to per-TF labels.
                           Structure: {window_size: {tf_name: ChannelLabels}}.
                           The `labels` field contains `labels_per_window[best_window]`.
        per_window_features: Dict mapping window sizes to FullFeatures objects.
                             Contains features extracted for each window (e.g., {10: FullFeatures, 20: FullFeatures, ...}).
                             Enables models to see features from all windows simultaneously.
                             New in v11.0.0.

    Note:
        Native per-TF labels are generated by:
        1. Resampling OHLC to each timeframe
        2. Detecting channel at that TF's native resolution
        3. Scanning forward at that TF's bar count
        This means duration_bars is in native TF bars (not 5min bars scaled).

    Backward Compatibility:
        The `channel`, `features`, and `labels` fields are maintained for backward compatibility.
        They always contain the best window's channel, features, and labels respectively.
        New code should use `channels`, `best_window`, `labels_per_window`, and
        `per_window_features` for full multi-window support.
    """
    timestamp: pd.Timestamp
    channel_end_idx: int
    channel: Channel  # Best channel (same as channels[best_window])
    features: FullFeatures  # Best window features (same as per_window_features[best_window])
    labels: Dict[str, ChannelLabels]  # Best window labels (same as labels_per_window[best_window])
    channels: Dict[int, Channel] = None  # All channels keyed by window size
    best_window: int = None  # Which window was selected as best
    labels_per_window: Dict[int, Dict[str, ChannelLabels]] = None  # Labels for each window
    per_window_features: Dict[int, FullFeatures] = None  # Features for each window (v11.0.0+)

    def get_features_for_window(self, window: int) -> Optional[FullFeatures]:
        """
        Get FullFeatures for a specific window.

        Args:
            window: Window size (e.g., 10, 20, 30, ...)

        Returns:
            FullFeatures object for the specified window, or None if window not available

        Example:
            features_20 = sample.get_features_for_window(20)
            if features_20 is not None:
                print(f"Position: {features_20.tsla['5min'].position}")
        """
        if self.per_window_features is None:
            return None
        return self.per_window_features.get(window)

    def has_multi_window_features(self) -> bool:
        """
        Check if this sample has multi-window features (v11.0.0+).

        Returns:
            True if per_window_features contains multiple windows, False otherwise

        Example:
            if sample.has_multi_window_features():
                print("Full multi-window features available")
            else:
                print("Single-window only (v10 or earlier)")
        """
        return self.per_window_features is not None and len(self.per_window_features) > 1

    def get_window_count(self) -> int:
        """
        Get the number of windows with extracted features.

        Returns:
            Number of windows in per_window_features, or 0 if not available

        Example:
            count = sample.get_window_count()
            print(f"Sample has features for {count} windows")
        """
        if self.per_window_features is None:
            return 0
        return len(self.per_window_features)
