#!/bin/bash

# Performance Summary Display Script
# Shows key performance metrics from C++ vs Python benchmark

echo "════════════════════════════════════════════════════════════════════════"
echo "           V15 C++ SCANNER PERFORMANCE BENCHMARK RESULTS"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Test Configuration:"
echo "  • Dataset: TSLA & SPY (440,404 bars, 2015-2025)"
echo "  • Samples: 1,000 channel samples"
echo "  • Channels detected: 212,159"
echo "  • Platform: macOS Apple Silicon"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "                         EXECUTION TIMES"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %15s %15s %15s\n" "Implementation" "Total Time" "Time/Sample" "Samples/sec"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %15s %15s %15s\n" "Python (1 worker)" "7723.9s" "7724 ms" "0.13"
printf "%-25s %15s %15s %15s\n" "C++ (1 worker)" "25.6s" "25.6 ms" "39.12"
printf "%-25s %15s %15s %15s\n" "C++ (8 workers)" "6.7s" "6.7 ms" "148.30"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "                         SPEEDUP ANALYSIS"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %15s %20s\n" "Configuration" "Speedup" "vs 10x Target"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %15s %20s\n" "C++ (1 worker)" "301.7x" "30.2x over target"
printf "%-25s %15s %20s\n" "C++ (8 workers)" "1152.8x" "115.3x over target"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "                      PHASE BREAKDOWN (1000 samples)"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %12s %12s %12s\n" "Phase" "Python" "C++ (1w)" "C++ (8w)"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %12s %12s %12s\n" "Pass 1 (channels)" "70.7s" "1.2s" "1.0s"
printf "%-25s %12s %12s %12s\n" "Pass 2 (labels)" "153.2s" "5.7s" "0.5s"
printf "%-25s %12s %12s %12s\n" "Pass 3 (samples)" "7500s*" "17.1s" "5.0s"
echo "────────────────────────────────────────────────────────────────────────"
printf "%-25s %12s %12s %12s\n" "TOTAL" "7724s" "25.6s" "6.7s"
echo "────────────────────────────────────────────────────────────────────────"
echo "* Python Pass 3 projected from observed 96s/batch rate"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo "                       PARALLEL EFFICIENCY"
echo "────────────────────────────────────────────────────────────────────────"
echo "  Workers: 8"
echo "  Speedup: 3.82x (vs 1 worker)"
echo "  Efficiency: 47.8%"
echo ""
echo "  Pass 3 Parallelization:"
echo "    • 1 worker:  17.1s"
echo "    • 8 workers:  5.0s"
echo "    • Speedup:    3.42x"
echo "    • Efficiency: 42.8%"
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "                            CONCLUSION"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "  ✓ TARGET ACHIEVED: 10x speedup goal"
echo "  ✓ EXCEEDED BY: 30x to 115x (depending on workers)"
echo "  ✓ STATUS: Production ready, no optimization needed"
echo ""
echo "  Key Wins:"
echo "    • Single-threaded: 301.7x faster than Python"
echo "    • Multi-threaded:  1152.8x faster than Python"
echo "    • Pass 3 speedup:  438.6x to 1500x improvement"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Full report: /Users/frank/Desktop/CodingProjects/x14/v15_cpp/PERFORMANCE_REPORT.md"
echo ""
