"""
Type definitions for training module.

This module contains shared types used across the training package,
specifically designed to avoid torch imports in scan workers.
"""

import pandas as pd
from dataclasses import dataclass
from typing import Dict, Optional

from ..core.channel import Channel
from ..features.full_features import FullFeatures
from .labels import ChannelLabels


@dataclass
class ChannelSample:
    """
    A single training sample consisting of a valid channel + its features and labels.

    Supports multi-window channel detection where channels are detected using
    different lookback window sizes, and the best window is selected.

    Attributes:
        timestamp: When this channel ends (last bar of detection window)
        channel_end_idx: Index in the full dataset where channel ends
        channel: The best detected Channel object (from best_window)
        features: FullFeatures extracted at channel end
        labels: Dict mapping TF names to ChannelLabels for the best window.
                Each TF has independently generated labels with proper scaling.
                Some TFs may have None if channel detection failed at that TF.
        channels: Dict mapping window sizes to Channel objects. Contains all
                  detected channels from different window sizes (e.g., {50: Channel, 100: Channel}).
        best_window: The window size that was selected as the best channel.
                     The `channel` field contains `channels[best_window]`.
        labels_per_window: Dict mapping window sizes to per-TF labels.
                           Structure: {window_size: {tf_name: ChannelLabels}}.
                           The `labels` field contains `labels_per_window[best_window]`.

    Note:
        Native per-TF labels are generated by:
        1. Resampling OHLC to each timeframe
        2. Detecting channel at that TF's native resolution
        3. Scanning forward at that TF's bar count
        This means duration_bars is in native TF bars (not 5min bars scaled).

    Backward Compatibility:
        The `channel` and `labels` fields are maintained for backward compatibility.
        They always contain the best window's channel and labels respectively.
        New code should use `channels`, `best_window`, and `labels_per_window`
        for full multi-window support.
    """
    timestamp: pd.Timestamp
    channel_end_idx: int
    channel: Channel  # Best channel (same as channels[best_window])
    features: FullFeatures
    labels: Dict[str, ChannelLabels]  # Best window labels (same as labels_per_window[best_window])
    channels: Dict[int, Channel] = None  # All channels keyed by window size
    best_window: int = None  # Which window was selected as best
    labels_per_window: Dict[int, Dict[str, ChannelLabels]] = None  # Labels for each window
